version: '3.7'
services: 
    serviciobackend:
        build: 
            context: .
            dockerfile: DockerFile
        ports: 
            - "8080:8080"
        restart: always
        environment: 
            RDS_HOSTNAME: mysql
        depends_on: 
            - mysql
        networks: 
            - backend
    mysql:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        restart: always
        environment: 
            MYSQL_DATABASE: todos
            MYSQL_ROOT_PASSWORD: dummypassword 
            MYSQL_USER: todos-user
            MYSQL_PASSWORD: dummytodos
        volumes: 
            - mysql-db:/var/lib/mysql
        networks: 
            - backend
volumes: 
    mysql-db
networks: 
    backends: